import type { Oppgave } from "../typer";

function o(
  del: Omit<Oppgave, "id"> & { id?: string },
  id: string,
): Oppgave {
  return { ...del, id };
}

export const ALLE_OPPGAVER: Oppgave[] = [
  o(
    {
      type: "bokstavlyd",
      nivaa: "forste",
      prompt: "Hvilken bokstav sier sss?",
      tale: "s",
      valg: ["S", "M", "L", "A"],
      fasit: "S",
      hint: "Sol begynner på sss.",
      belonning: "krystall",
    },
    "f-lyd-s",
  ),
  o(
    {
      type: "bokstavlyd",
      nivaa: "forste",
      prompt: "Hvilken bokstav sier mmm?",
      tale: "m",
      valg: ["R", "M", "I", "U"],
      fasit: "M",
      hint: "Mus begynner på mmm.",
      belonning: "krystall",
    },
    "f-lyd-m",
  ),
  o(
    {
      type: "bokstavlyd",
      nivaa: "forste",
      prompt: "Hvilken bokstav sier aaa?",
      tale: "a",
      valg: ["O", "E", "A", "I"],
      fasit: "A",
      hint: "Ape begynner på aaa.",
      belonning: "krystall",
    },
    "f-lyd-a",
  ),
  o(
    {
      type: "bokstavlyd",
      nivaa: "forste",
      prompt: "Hvilken bokstav sier lll?",
      tale: "l",
      valg: ["L", "B", "T", "N"],
      fasit: "L",
      hint: "Lam begynner på lll.",
      belonning: "krystall",
    },
    "f-lyd-l",
  ),
  o(
    {
      type: "bokstavlyd",
      nivaa: "forste",
      prompt: "Hvilken bokstav sier iii?",
      tale: "i",
      valg: ["E", "Y", "I", "Å"],
      fasit: "I",
      hint: "Is begynner på iii.",
      belonning: "krystall",
    },
    "f-lyd-i",
  ),
  o(
    {
      type: "bokstavlyd",
      nivaa: "forste",
      prompt: "Hvilken bokstav sier øøø?",
      tale: "ø",
      valg: ["Ø", "O", "Æ", "U"],
      fasit: "Ø",
      hint: "Øre begynner på øøø.",
      belonning: "krystall",
    },
    "f-lyd-oe",
  ),
  o(
    {
      type: "bokstavlyd",
      nivaa: "forste",
      prompt: "Hvilken bokstav sier æææ?",
      tale: "æ",
      valg: ["A", "Æ", "E", "Ø"],
      fasit: "Æ",
      hint: "Æsj begynner på æææ.",
      belonning: "krystall",
    },
    "f-lyd-ae",
  ),
  o(
    {
      type: "bokstavlyd",
      nivaa: "forste",
      prompt: "Hvilken bokstav sier ååå?",
      tale: "å",
      valg: ["Å", "O", "A", "Ø"],
      fasit: "Å",
      hint: "Ål begynner på ååå.",
      belonning: "krystall",
    },
    "f-lyd-aa",
  ),
  o(
    {
      type: "forstelyd",
      nivaa: "forste",
      prompt: "Hva begynner sol på?",
      tale: "sol",
      valg: ["S", "L", "O", "M"],
      fasit: "S",
      hint: "Sol begynner på sss.",
      belonning: "krystall",
      bilde: "sol",
    },
    "f-forst-sol",
  ),
  o(
    {
      type: "forstelyd",
      nivaa: "forste",
      prompt: "Hva begynner hus på?",
      tale: "hus",
      valg: ["H", "U", "S", "M"],
      fasit: "H",
      hint: "Hus begynner på hhh.",
      belonning: "krystall",
      bilde: "hus",
    },
    "f-forst-hus",
  ),
  o(
    {
      type: "forstelyd",
      nivaa: "forste",
      prompt: "Hva begynner mus på?",
      tale: "mus",
      valg: ["U", "S", "M", "B"],
      fasit: "M",
      hint: "Mus begynner på mmm.",
      belonning: "krystall",
      bilde: "mus",
    },
    "f-forst-mus",
  ),
  o(
    {
      type: "forstelyd",
      nivaa: "forste",
      prompt: "Hva begynner lam på?",
      tale: "lam",
      valg: ["L", "A", "P", "K"],
      fasit: "L",
      hint: "Lam begynner på lll.",
      belonning: "krystall",
      bilde: "lam",
    },
    "f-forst-lam",
  ),
  o(
    {
      type: "forstelyd",
      nivaa: "forste",
      prompt: "Hva begynner bil på?",
      tale: "bil",
      valg: ["B", "I", "P", "D"],
      fasit: "B",
      hint: "Bil begynner på bbb.",
      belonning: "krystall",
      bilde: "bil",
    },
    "f-forst-bil",
  ),
  o(
    {
      type: "storLiten",
      nivaa: "forste",
      prompt: "Finn den lille bokstaven til M",
      tale: "stor m, liten m",
      valg: ["n", "m", "w", "h"],
      fasit: "m",
      hint: "Stor M hører sammen med liten m.",
      belonning: "krystall",
    },
    "f-stor-m",
  ),
  o(
    {
      type: "storLiten",
      nivaa: "forste",
      prompt: "Finn den lille bokstaven til S",
      tale: "stor s, liten s",
      valg: ["s", "z", "c", "e"],
      fasit: "s",
      hint: "Stor S hører sammen med liten s.",
      belonning: "krystall",
    },
    "f-stor-s",
  ),
  o(
    {
      type: "storLiten",
      nivaa: "forste",
      prompt: "Finn den store bokstaven til a",
      tale: "liten a, stor a",
      valg: ["A", "O", "Æ", "Å"],
      fasit: "A",
      hint: "Liten a hører sammen med stor A.",
      belonning: "krystall",
    },
    "f-stor-a",
  ),
  o(
    {
      type: "storLiten",
      nivaa: "forste",
      prompt: "Finn den lille bokstaven til Ø",
      tale: "stor ø, liten ø",
      valg: ["o", "ø", "æ", "å"],
      fasit: "ø",
      hint: "Stor Ø hører sammen med liten ø.",
      belonning: "krystall",
    },
    "f-stor-oe",
  ),
  o(
    {
      type: "tegning",
      nivaa: "forste",
      prompt: "Tegn bokstaven O oppå spøkelset",
      tale: "o. Tegn o.",
      valg: [],
      fasit: "O",
      hint: "O er en rund ring.",
      belonning: "krystall",
      omriss: "O",
    },
    "f-tegn-o",
  ),
  o(
    {
      type: "tegning",
      nivaa: "forste",
      prompt: "Tegn bokstaven L oppå spøkelset",
      tale: "l. Tegn l.",
      valg: [],
      fasit: "L",
      hint: "L er en strek ned og en strek til siden.",
      belonning: "krystall",
      omriss: "L",
    },
    "f-tegn-l",
  ),
  o(
    {
      type: "tegning",
      nivaa: "forste",
      prompt: "Tegn bokstaven I oppå spøkelset",
      tale: "i. Tegn i.",
      valg: [],
      fasit: "I",
      hint: "I er en rett strek.",
      belonning: "krystall",
      omriss: "I",
    },
    "f-tegn-i",
  ),
  o(
    {
      type: "trekkSammen",
      nivaa: "andre",
      prompt: "Hva blir sss – ooo – lll?",
      tale: "s. o. l.",
      valg: ["sol", "los", "sil", "lam"],
      fasit: "sol",
      hint: "Trekk lydene sammen: sss-ooo-lll blir sol.",
      belonning: "krystall",
    },
    "a-trekk-sol",
  ),
  o(
    {
      type: "trekkSammen",
      nivaa: "andre",
      prompt: "Hva blir mmm – uuu – sss?",
      tale: "m. u. s.",
      valg: ["sum", "mus", "hus", "mas"],
      fasit: "mus",
      hint: "mmm-uuu-sss blir mus.",
      belonning: "krystall",
    },
    "a-trekk-mus",
  ),
  o(
    {
      type: "trekkSammen",
      nivaa: "andre",
      prompt: "Hva blir hhh – uuu – sss?",
      tale: "h. u. s.",
      valg: ["hus", "mus", "has", "sul"],
      fasit: "hus",
      hint: "hhh-uuu-sss blir hus.",
      belonning: "krystall",
    },
    "a-trekk-hus",
  ),
  o(
    {
      type: "trekkSammen",
      nivaa: "andre",
      prompt: "Hva blir bbb – iii – lll?",
      tale: "b. i. l.",
      valg: ["bil", "pil", "lib", "bal"],
      fasit: "bil",
      hint: "bbb-iii-lll blir bil.",
      belonning: "krystall",
    },
    "a-trekk-bil",
  ),
  o(
    {
      type: "rim",
      nivaa: "andre",
      prompt: "Hva rimer på hus?",
      tale: "hus",
      valg: ["mus", "lam", "sol", "mat"],
      fasit: "mus",
      hint: "Hus og mus ender likt: uss.",
      belonning: "diamant",
    },
    "a-rim-hus",
  ),
  o(
    {
      type: "rim",
      nivaa: "andre",
      prompt: "Hva rimer på bil?",
      tale: "bil",
      valg: ["pil", "hus", "sol", "ram"],
      fasit: "pil",
      hint: "Bil og pil ender likt: ill.",
      belonning: "diamant",
    },
    "a-rim-bil",
  ),
  o(
    {
      type: "rim",
      nivaa: "andre",
      prompt: "Hva rimer på mat?",
      tale: "mat",
      valg: ["hat", "mus", "sol", "le"],
      fasit: "hat",
      hint: "Mat og hat ender likt: att.",
      belonning: "diamant",
    },
    "a-rim-mat",
  ),
  o(
    {
      type: "stavelser",
      nivaa: "andre",
      prompt: "Hvor mange klapp har ordet skole?",
      tale: "sko-le",
      valg: ["1", "2", "3", "4"],
      fasit: "2",
      hint: "Sko – le. To klapp.",
      belonning: "krystall",
    },
    "a-stav-skole",
  ),
  o(
    {
      type: "stavelser",
      nivaa: "andre",
      prompt: "Hvor mange klapp har ordet sol?",
      tale: "sol",
      valg: ["1", "2", "3", "4"],
      fasit: "1",
      hint: "Sol er ett klapp.",
      belonning: "krystall",
    },
    "a-stav-sol",
  ),
  o(
    {
      type: "stavelser",
      nivaa: "andre",
      prompt: "Hvor mange klapp har ordet banana?",
      tale: "ba-na-na",
      valg: ["2", "3", "4", "1"],
      fasit: "3",
      hint: "Ba – na – na. Tre klapp.",
      belonning: "krystall",
    },
    "a-stav-banana",
  ),
  o(
    {
      type: "byggOrd",
      nivaa: "andre",
      prompt: "Sett bokstavene i rett rekkefølge: L O S",
      tale: "l. o. s. Hvilket ord?",
      valg: ["sol", "los", "slo", "ols"],
      fasit: "sol",
      hint: "S først, så O, så L. Sol.",
      belonning: "diamant",
    },
    "a-bygg-sol",
  ),
  o(
    {
      type: "byggOrd",
      nivaa: "andre",
      prompt: "Sett bokstavene i rett rekkefølge: S U M",
      tale: "Hvilket ord blir det?",
      valg: ["mus", "sum", "ums", "smu"],
      fasit: "mus",
      hint: "M først: mus.",
      belonning: "diamant",
    },
    "a-bygg-mus",
  ),
  o(
    {
      type: "byttLyd",
      nivaa: "utfordrende",
      prompt: "Bytt b i bil med p. Hva blir det?",
      tale: "bil. Bytt b med p.",
      valg: ["pil", "sil", "mil", "il"],
      fasit: "pil",
      hint: "bbb blir ppp: pil.",
      belonning: "diamant",
    },
    "u-bytt-bil",
  ),
  o(
    {
      type: "byttLyd",
      nivaa: "utfordrende",
      prompt: "Bytt h i hus med m. Hva blir det?",
      tale: "hus. Bytt h med m.",
      valg: ["mus", "lus", "hus", "sus"],
      fasit: "mus",
      hint: "hhh blir mmm: mus.",
      belonning: "diamant",
    },
    "u-bytt-hus",
  ),
  o(
    {
      type: "byttLyd",
      nivaa: "utfordrende",
      prompt: "Ta bort s i sol. Hva blir igjen?",
      tale: "sol. Ta bort s.",
      valg: ["ol", "so", "sl", "lo"],
      fasit: "ol",
      hint: "Uten sss blir det ol.",
      belonning: "diamant",
    },
    "u-bytt-sol",
  ),
  o(
    {
      type: "manglende",
      nivaa: "utfordrende",
      prompt: "Hvilken bokstav mangler? sk_le",
      tale: "skole. Hvilken bokstav mangler?",
      valg: ["o", "a", "u", "i"],
      fasit: "o",
      hint: "Sko-le. Bokstaven o.",
      belonning: "diamant",
    },
    "u-mang-skole",
  ),
  o(
    {
      type: "manglende",
      nivaa: "utfordrende",
      prompt: "Hvilken bokstav mangler? _us",
      tale: "hus. Hvilken bokstav først?",
      valg: ["h", "m", "l", "b"],
      fasit: "h",
      hint: "Hus begynner på h.",
      belonning: "diamant",
    },
    "u-mang-hus",
  ),
  o(
    {
      type: "manglende",
      nivaa: "utfordrende",
      prompt: "Hvilket ord passer? Jeg ___ til skolen.",
      tale: "Jeg går til skolen. Hvilket ord?",
      valg: ["går", "sol", "mus", "hat"],
      fasit: "går",
      hint: "Jeg går til skolen.",
      belonning: "diamant",
    },
    "u-mang-gar",
  ),
  o(
    {
      type: "manglende",
      nivaa: "utfordrende",
      prompt: "Hvilken bokstav mangler? l_m",
      tale: "lam. Hvilken bokstav i midten?",
      valg: ["a", "e", "i", "o"],
      fasit: "a",
      hint: "Lam har a i midten.",
      belonning: "diamant",
    },
    "u-mang-lam",
  ),
];
